permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: "https://cheenwe.cn"

title: "cheenwe的博客"
email: "cxhyun@126.com"
description: "记录开发中点滴"
beian: "豫ICP备16011691号"
github_username:  "cheenwe"
swiftype_searchId: "9TDAXeK2smEEtWndRZJB"
duoshuo_shortname: "cheenwe"
baidu_tongji_id: "e5ffc49003a8ce5cec5c267ebf0172ca"

comment_client_id: "51bf94ce166ab21b605b"
comment_client_secret: "ac9e946ee16ddeb914212f37269a1bfacdf93246"
comment_user: "cheenwe"
comment_repo: "comment"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js, toc.js]



url: "https://cheenwe.cn"
imgrepo: "https://cheenwe.cn/static/img"

# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"

